name: cos424
channels:
  - https://conda.anaconda.org/menpo
  - conda-forge
dependencies:
  - python==2.7.14
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scikit-learn
  - scipy
  - nltk
  - pip:
    - argparse
    - tensorflow-gpu==1.3
    - tqdm
